-- Create a table for public profiles (extends auth.users)
create table profiles (
  id uuid references auth.users on delete cascade not null primary key,
  email text,
  full_name text,
  phone text,
  address text,
  city text,
  state text,
  zip text,
  updated_at timestamp with time zone
);

-- Establish Row Level Security (RLS) for profiles
alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone." on profiles
  for select using (true);

create policy "Users can insert their own profile." on profiles
  for insert with check (auth.uid() = id);

create policy "Users can update own profile." on profiles
  for update using (auth.uid() = id);

-- Create a table for registrations
create table registrations (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  created_at timestamp with time zone using (now() at time zone 'utc') default now(),
  
  -- Participant Details (snapshot in case profile changes)
  student_name text,
  dob date,
  guru_name text,
  
  -- Competition Details
  category text, -- 'Music' or 'Dance'
  competition_item text, -- 'Carnatic Vocal', 'Violin', etc.
  
  -- Song Details (stored as JSON)
  songs jsonb, -- [{raga: 'Kalyani', tala: 'Adi', song: 'Vanajakshi'}]
  
  -- Status flow
  status text default 'pending_payment', -- 'pending_payment', 'confirmed'
  payment_id text, -- transaction id
  
  unique(user_id, competition_item) -- Prevent duplicate reg for same item
);

-- RLS for registrations
alter table registrations enable row level security;

create policy "Users can view own registrations." on registrations
  for select using (auth.uid() = user_id);

create policy "Users can insert own registrations." on registrations
  for insert with check (auth.uid() = user_id);

create policy "Users can update own registrations." on registrations
  for update using (auth.uid() = user_id);

-- Function to handle new user creation automatically
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, full_name)
  values (new.id, new.email, new.raw_user_meta_data->>'full_name');
  return new;
end;
$$ language plpgsql security definer;

-- Trigger the function every time a user is created
create or replace trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
