-- Create a table for public profiles (extends auth.users)
create table profiles (
  id uuid references auth.users on delete cascade not null primary key,
  email text,
  full_name text,
  phone text,
  address text,
  city text,
  state text,
  zip text,
  updated_at timestamp with time zone
);

-- Establish Row Level Security (RLS) for profiles
alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone." on profiles
  for select using (true);

create policy "Users can insert their own profile." on profiles
  for insert with check (auth.uid() = id);

create policy "Users can update own profile." on profiles
  for update using (auth.uid() = id);

-- Create a table for registrations
create table registrations (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  created_at timestamp with time zone using (now() at time zone 'utc') default now(),
  
  -- Participant Details (snapshot in case profile changes)
  student_name text,
  dob date,
  guru_name text,
  
  -- Competition Details
  category text, -- 'Music' or 'Dance'
  competition_item text, -- 'Carnatic Vocal', 'Violin', etc.
  
  -- Song Details (stored as JSON)
  songs jsonb, -- [{raga: 'Kalyani', tala: 'Adi', song: 'Vanajakshi'}]
  
  -- Status flow
  status text default 'pending_payment', -- 'pending_payment', 'confirmed'
  payment_id text, -- transaction id
  
  unique(user_id, competition_item) -- Prevent duplicate reg for same item
);

-- RLS for registrations
alter table registrations enable row level security;

create policy "Users can view own registrations." on registrations
  for select using (auth.uid() = user_id);

create policy "Users can insert own registrations." on registrations
  for insert with check (auth.uid() = user_id);

create policy "Users can update own registrations." on registrations
  for update using (auth.uid() = user_id);

-- Function to handle new user creation automatically
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, full_name)
  values (new.id, new.email, new.raw_user_meta_data->>'full_name');
  return new;
end;
$$ language plpgsql security definer;

-- Trigger the function every time a user is created
create or replace trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Create a table for contact form messages
create table contact_messages (
  id uuid default gen_random_uuid() primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  first_name text not null,
  last_name text not null,
  email text not null,
  subject text not null,
  message text not null,
  
  -- Tracking if the message was read/handled by admin
  status text default 'unread'
);

-- RLS for contact messages
alter table contact_messages enable row level security;

-- Allow anyone (even anonymous) to insert a contact message
create policy "Anyone can submit a contact message" on contact_messages
  for insert with check (true);

-- Only authenticated users (or admins) should be able to view them.
-- Assuming admins are tracking them. For now, allow no one to read them publicly.
create policy "Only authenticated users can view messages" on contact_messages
  for select using (auth.role() = 'authenticated');

-- ==========================================
-- RLS Policy for blog_posts table
-- ==========================================
alter table public.blog_posts enable row level security;

-- Allow anyone to read blog posts
create policy "Anyone can view blog posts" on public.blog_posts
  for select using (true);

-- Allow only authenticated users (admins) to modify blog posts
create policy "Only authenticated users can insert blog posts" on public.blog_posts
  for insert with check (auth.role() = 'authenticated');
  
create policy "Only authenticated users can update blog posts" on public.blog_posts
  for update using (auth.role() = 'authenticated');

create policy "Only authenticated users can delete blog posts" on public.blog_posts
  for delete using (auth.role() = 'authenticated');
